resources:
  - name: GetFiles
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      aql: '{"items.find": {"repo": {"$match:": "pypi-virtual"}}}'


pipelines:
  - name: PropertyDemo
    steps:
      - name: ArtifactoryFiles
        type: Bash
        configuration:
          inputResources:
            - name: GetFiles
        execution:
          onExecute:
            - cat $HOME/.jfrog/logs/jfrog-cli*
            - ls
